zarr_dir: "./data/zarr_files"
rosbag_dir: "./data/rawbags"
rosbag_type: ".db3"


print_times: True
arm_dof: 7

# zarr only
times_name: "tick"
joint_names: ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6", "joint_7", "robotiq_2f_85"]

# resource paths
scene_path: "./resources/scene_highcam.yaml"
urdf_path: "./resources/gen3_urdf/urdf/gen3.urdf"
gripper_urdf_path: "./resources/robotiq-2f-85_urdf/urdf/robotiq-2f-85.urdf"
blueprint_path: "./resources/kinova_bimanual_setup.rbl"
application_id: "kinova_bimanual_setup"

# visual preferences
point_radii: 0.0015
point_colorscheme: heatmap #mono or heatmap